from rewording import Tree, Node

tree = Tree('Новая схема')
tree.add_node(Node('я $координирую$ $работу$', ['устанавливать', 'команда']))
tree.add_node(Node('ты $координируешь$ $работой$', ['устанавливать', 'команда']))
tree.add_node(Node('он $координирует$ $работами$', ['устанавливать', 'команда']))
tree.add_node(Node('они $координируют$ $работой$', ['устанавливать', 'команда']))
tree.add_node(Node('она $координировала$ $работой$', ['устанавливать', 'команда']))
tree.add_node(Node('они $координировали$', ['устанавливать']))
tree.children[5].add_child(Node('мы $работаем$', ['устанавливать']))
tree.children[5].add_child(Node('мы $работаем$', ['делать']))
tree.children[5].apply_template()
#node = Node('я $координирую$ $жопу$', ['устанавливать', 'команда'])
#node.add_child(Node('я $координирую$ $жопу$', ['устанавливать', 'правило']))
#node.add_child(Node('они $координируют$ $жопы$', ['устанавливать', 'правило']))
#tree.add_node(node)
#tree.add_node(Node('$формирование$', 'изменение'))
#tree.add_node(Node('$формирования$', 'изменение'))
#tree.add_node(Node('$формированию$', 'изменение'))
#tree.add_node(Node('$формирование$', 'изменение'))
#tree.add_node(Node('$формирование$', 'изменение'))
#tree.add_node(Node('о $формировании$', 'изменение'))

#tree.apply_all()
#tree.print_all_results()

#tree.delete_child(1)
#tree.children[0].delete_child(0)
tree.print_all_results()
tree.apply_all()
tree.print_all_results()